version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    container_name: auth-portainer
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=ivisit-network"
    #   # Frontend
    #   - "traefik.http.routers.portainer.rule=Host(`${IVISIT_PORTAINER_DOMAIN:-ivisit-portainer.testlocal.ir}`)"
    #   - "traefik.http.routers.portainer.service=portainer"
    #   - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    #   # edge
    #   - "traefik.http.routers.portaineredge.rule=Host(`${IVISIT_PORTAINER_EDGE_DOMAIN:-ivisit-portainer-edge.testlocal.ir}`)"
    #   - "traefik.http.routers.portaineredge.service=portaineredge"
    #   - "traefik.http.services.portaineredge.loadbalancer.server.port=8000"

    networks:
      - general-network

    ports:
      - ${PORTAINER_EXTERNAL_PORT:-9000}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

  traefik:
    image: traefik:latest
    restart: unless-stopped
    volumes:
      - ./certs:/ssl-certs
      - ./traefik_config:/etc/traefik
      - ./traefik/log:/log/traefik.log
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - general-network
    labels:
      - "traefik.http.routers.backend.rule=Host(`${TECH_TRAEFIK_DOMAIN:-techtraefik.testlocal.ir}`)"
      - "traefik.http.routers.backend.service=backend@internal"
      # - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.backend.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersFile=/etc/traefik/users"
      - "traefik.docker.network=general-network"

    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      # (Optional) Expose Dashboard
      - "8000:8000" # Don't do this in production! --> dashboard

  # traefik2:
  #     image: traefik:latest
  #     container_name: traefik
  #     restart: always
  #     volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - ./traefik/traefik.toml:/traefik.toml
  #       - ./traefik/acme.json:/acme.json
  #     networks:
  #       - general-network
  #     labels:
  #       - "traefik.frontend.rule=Host:techtraefik.testlocal.ir"
  #       - "traefik.port=8000"
  #     command: --docker --docker.domain=techtraefik.testlocal.ir
  #     ports:
  #       - 80:80
  #       - 443:443
      
# create network --> to use backend and frontend externally
networks:
  general-network:
    name: general-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
