FROM nginx

# copy my custom nginx-config-file to server (server_path)
COPY ./config/ /etc/nginx/conf.d/

# for just nginx.conf copy to server
# first create nginx.conf file and config it
# COPY nginx.conf /etc/nginx/conf.d/default.conf